sudo: required
services:
  - docker
language: node_js
node_js:
  - "10"
  - "14"
  - "12"
install:
  - npm install
script:
  - npm test
  - npm run lint
deploy:
  provider: script
  script: bash scripts/publish_docker.sh
  on:
    branch: master
