# https://docs.travis-ci.com/user/languages/javascript-with-nodejs
dist: jammy
sudo: required
services:
  - docker
language: node_js
node_js:
  - "node"
  - "lts/*"
  - "14"
  - "16"
  - "17"
  - "18"
install:
  - npm install
script:
  - npm test
  - npm run lint
deploy:
  provider: script
  script: bash scripts/publish_docker.sh
  on:
    branch: master
